# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       - MONGO_URL=mongodb://mongo:27017/mydatabase
#     depends_on:
#       - mongo
#     volumes:
#       - .:/usr/src/app

#   mongo:
#     image: mongo:4.4
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:

#   version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       - POSTGRES_URL=postgresql://postgres:password@postgres:5432/mydatabase
#     depends_on:
#       - postgres
#     volumes:
#       - .:/usr/src/app

#   postgres:
#     image: postgres:13
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:
